openshift/osd-network-verifier

.gitignore
cmd/egress/cmd.go
pkg/cloudclient/aws/aws.go
pkg/cloudclient/aws/private.go
pkg/cloudclient/cloudclient.go
pkg/cloudclient/gcp/gcp.go

This adds `--image-id` as a CLI parameter and removes the hard-coded AMI ID in the aws cloudclient pkg.
```
$ ./osd-network-verifier egress --help
Usage:
osd-network-verifier egress [flags]
Flags:
-h, --help               help for egress
--image-id string    ID of cloud image
--subnet-id string   ID of the source subnet
```
This also makes a quick edit to the .gitignore to ignore *.swp files for Vim users.

Add cloud image ID as a CLI option

---

build/Dockerfile

.5 seconds is a bit short and causing flakiness, lengthening to 1 second is still reasonable and seems to reduce the flakiness

Lengthen timeout to 1 second

---

README.md
cmd/byovpc/cmd.go
cmd/egress/cmd.go
pkg/cloudclient/aws/aws.go
pkg/cloudclient/aws/private.go
pkg/cloudclient/cloudclient.go
pkg/cloudclient/gcp/gcp.go

This adds a new command-line option to the osd-network-verifier tool `--cloud-tags` allowing a comma-seperated list of `key=value` pairs to be provided to the tool. The tool will use these key/value pairs to tag all EC2 instances created. The default list of tags is `osd-network-verifier=owned`, similar to the account operator's tags as defined in templated tooling.
```
$ ./osd-network-verifier egress --help
Usage:
osd-network-verifier egress [flags]
Flags:
--cloud-tags stringToString   Comma-seperated list of tags to assign to cloud resources (default [osd-network-verifier=owned])
```

Implement configurable tags for cloud resources

---

cmd/egress/cmd.go
pkg/cloudclient/aws/private.go

This includes several changes due to an issue that was revealed while adding the initial change to properly check for userdata completion:
1. Userdata script completion checking is added/changed to use regexp
2. Moving the default instance type to use a "nitro" t3.micro instance that supports continuous console log output
3. Providing the `latest=true` request parameter to the GetConsoleOutput EC2 API call to ensure the console log is updated before being provided in the response
4. Adding a default region `us-east-2` instead of assuming the AWS_DEFAULT_REGION variable is defined. We may want to consider add this as a command-line option as well.
This resolves a major issue where console output may not include the full userdata execution, depending on how long the userdata script takes to …

Wait for verification that userdata script has completed and move to nitro instance type

---

Makefile

The go flags were previously set prior to the run of the command,
resulting in two issues:
1. The exit code of the `make build` command was always 0 since -mod=mod
would always return 0
2. The go commands didn't actually receive the flag
Note that `go mod` and `go fmt` don't accept/honor the -mod flag, so the
GOFLAGS have been removed from those.
Verified with:
```
$ make ; echo $?
Makefile:29: warning: overriding recipe for target 'skopeo-push'
standard.mk:40: warning: ignoring old recipe for target 'skopeo-push'
go fmt ./...
go mod tidy
go build -mod=mod .
0
$ echo "BREAK" >> pkg/cloudclient/aws/aws.go 
$ make ; echo $?
Makefile:29: warning: overriding recipe for target 'skopeo-push'
standard.mk:40: warning: ignoring old recipe for target 'skopeo-push'
go fmt ./... …
```

Fix makefile go flags

---

cmd/byovpc/cmd.go
cmd/egress/cmd.go
pkg/cloudclient/aws/aws.go
pkg/cloudclient/aws/private.go
pkg/cloudclient/cloudclient.go
pkg/cloudclient/gcp/gcp.go

This adds the `--instance-type=...` CLI option with a default of `t3.micro` to the osd-network-verifier CLI.
This also adds a post-client-creation check that reaches out to EC2 to ensure that the provided instance type uses the "nitro" hypervisor. The nitro hypervisor is required to allow the tool to reliably collect the userdata script output.
Providing an invalid instance type will now result in an error:
```
$ ./osd-network-verifier egress --subnet-id=subnet-0560aed436f77a99e --debug=true --instance-type=foobar
Gathering description of instance type foobar from EC2
Unable to create AWS client: Instance type foobar is invalid: Unable to gather list of supported instance types from EC2: Instance type foobar does not exist
$ ./osd-network-verifier egress …
```

Adds instance type as CLI option and verifies hypervisor is nitro

---

build/bin/network-validator.go

https://issues.redhat.com/browse/OSD-9351
In the case where the script completes but one or more endpoints are not
reachable, we should exit with a 0 code instead of 1. This will help
ensure that the run of the docker image does not abort early when
endpoints are not reachable.
This change does mean that it will be more difficult to use the script
programatically outside of the existing osd-network-verifier tooling,
but as there is no use-case for that today this should be the most
reliable option.

[OSD-9351] Exit 0 when network validation script runs successfully

---

Makefile

Type: Bug
Currently the testing function doesn't actually run all the tests under osd-network-verifier
```shell
make test
Makefile:29: warning: overriding recipe for target 'skopeo-push'
standard.mk:40: warning: ignoring old recipe for target 'skopeo-push'
go test -mod=mod
?       github.com/openshift/osd-network-verifier       [no test files]
```
This PR transforms it to
```shell
make test
Makefile:29: warning: overriding recipe for target 'skopeo-push'
standard.mk:40: warning: ignoring old recipe for target 'skopeo-push'
go test -mod=mod ./...
?       github.com/openshift/osd-network-verifier       [no test files]
?       github.com/openshift/osd-network-verifier/build/bin     [no test files]
?       github.com/openshift/osd-network-verifier/cmd   [no test files]
? …
```

bug: fix running tests

---

hack/app_sre_build_push.sh

Removing `build` from containerization process as it's no needed
The build is currently breaking app-sre pipeline:  https://ci.int.devshift.net/view/osd-operators/job/openshift-osd-network-verifier-gh-build-main/1/console

ci: exclude build as it's already covered in dockerization

---

pkg/cloudclient/aws/private.go

As we have now the validator images in place: https://quay.io/repository/app-sre/osd-network-verifier?tag=latest&tab=tags

fix: update the image to the one that's in app-sre

---

cmd/egress/cmd.go

To align with the rest of Managed Openshift, this PR adds the `red-hat-managed: true` tag to the ec2 instance created by the verifier. Also adds a name tag for better identification.
REF: https://issues.redhat.com/browse/OSD-9874

Add Managed Openshift standard tag and Name tag

---

README.md
cmd/egress/cmd.go
main.go
pkg/cloudclient/aws/aws.go
pkg/cloudclient/aws/private.go
pkg/cloudclient/aws/private_test.go
pkg/cloudclient/cloudclient.go
pkg/cloudclient/gcp/gcp.go
pkg/cloudclient/gcp/gcp_test.go
pkg/output/output.go

Fix: https://issues.redhat.com/browse/OSD-9875
Example execution
```shell
AWS_ACCESS_KEY_ID=redacted AWS_SECRET_ACCESS_KEY=redacted ./osd-network-verifier egress --subnet-id subnet-024243d552dsomeid --region us-east-1
Created instance with ID: i-05924e5e7860de75f
EC2 Instance: i-05924e5e7860de75f Running
Gathering and parsing console log output...
Terminating ec2 instance with id i-05924e5e7860de75f
Summary:
printing out exceptions preventing onv from running:
-  [   29.347841] cloud-init[2255]: Cannot find a valid baseurl for repo: amzn2-core/2/x86_64
-  [   29.365916] cloud-init[2255]: Could not retrieve mirrorlist https://amazonlinux-2-repos-us-east-1.s3.dualstack.us-east-1.amazonaws.com/2/core/latest/x86_64/mirror.list error was
-  [ …
```

bug: handle the case when docker cannot be installed

---

README.md

This PR adds the list of AWS permissions required to run the osd-network-verifier to the README for documentation

Specify AWS permissions required to run the verifier

---

pkg/cloudclient/aws/private.go

Added a `BlockDeviceMapping` specification to `createEC2Instance()` such that all instances created by the verifier use encrypted EBS volumes by default. Volumes are encrypted with the AWS Managed KMS key and are automatically deleted upon instance termination.
This addresses OSD-10219, where the verifier fails on clusters that mandate encrypted storage universally.

Encrypt AWS instance EBS volume by default

---

pkg/cloudclient/aws/private.go
pkg/errors/errors.go
pkg/output/output.go

Fix: https://issues.redhat.com/browse/OSD-10574
**Example Executions**:
_against a subnet without an igw_
```shell
AWS_ACCESS_KEY_ID=XX AWS_SECRET_ACCESS_KEY=XXX ./osd-network-verifier egress --subnet-id subnet-00370fcf033c27bd8 --region us-east-1
Created instance with ID: i-00e3fadaefc6342f0
EC2 Instance: i-00e3fadaefc6342f0 Running
Gathering and parsing console log output...
Terminating ec2 instance with id i-00e3fadaefc6342f0
Summary:
printing out exceptions preventing onv from running:
-  egressURL error: [   28.639978] cloud-init[2256]: Cannot find a valid baseurl for repo: amzn2-core/2/x86_64
-  egressURL error: [   28.640090] cloud-init[2256]: Could not retrieve mirrorlist https://amazonlinux-2-repos-us-east-1.s3.dualstack.us-east-1.ama …
```

feat: use standardized errors for the output

---

README.md
cmd/egress/cmd.go
pkg/cloudclient/aws/aws.go
pkg/cloudclient/aws/private.go
pkg/cloudclient/aws/private_test.go
pkg/cloudclient/cloudclient.go
pkg/cloudclient/gcp/gcp.go
pkg/cloudclient/gcp/gcp_test.go

Added a `--kms-key-id <string>` CLI flag that allows the user to specify which KMS key should be used when encrypting the root volume of ONV-created instances. This option has also been added as a parameter (`kmsKeyID`) to the `ValidateEgress()` API function. Not specifying this key simply defaults back to the cloud account default KMS key.
Implementation-wise, adding this option as yet-another parameter to `createEC2Instance()` would have made that function's signature unreadably long, so I instead refactored the function such that it now takes in a param struct of type createEC2InstanceInput.
This addresses OSD-11084, where verifier users requested the ability to specify which KMS key is used for encryption.

Allow users to specify instance root volume encryption key

---

OWNERS

I hereby petition the royal council of network verifiers to recognize the contributions of a certain `abyrne55` as having fulfilled the requirements for the role known as **reviewer** as defined in the [1987 Charter of the Verifiers](https://www.youtube.com/watch?v=dQw4w9WgXcQ), and to confer such a distinguished title upon this individual, including all the responsibilities, privileges, and immunities appertaining thereto.
This addresses OSD-Y0L0, where the user only lives once, unless they're in the OWNERS file, in which case they're pretty much immortal (as long as us-east-1 doesn't go down).

Add abyrne55 as reviewer to OWNERS

---

pkg/cloudclient/aws/private.go

Second Fix: https://issues.redhat.com/browse/OSD-10574
**Example Executions:**
```shell
AWS_ACCESS_KEY_ID=XXX AWS_SECRET_ACCESS_KEY=XXX ./osd-network-verifier egress --subnet-id subnet-00370fcf033c27bd8 --region us-east-1
Created instance with ID: i-0fac8fe720cc59071
EC2 Instance: i-0fac8fe720cc59071 Running
Gathering and parsing console log output...
Terminating ec2 instance with id i-0fac8fe720cc59071
Summary:
printing out exceptions preventing onv from running:
-  egressURL error: internet connectivity problem: please ensure there's internet access in given vpc subnets
printing out errors faced during the execution:
Failure!
```

feat: mask docker related errors

---

cmd/byovpc/cmd.go
cmd/egress/cmd.go

AWS_DEFAULT_REGION is specific to cli configuration, whereas
AWS_REGION is SDK compatible and takes precedent. Given the verifier
utilizes the SDK, AWS_REGION should be used.
Ref: https://issues.redhat.com/browse/OSD-11348

Use AWS_REGION instead of AWS_DEFAULT_REGION

---

build/bin/network-validator.go
build/config/config.yaml
go.mod
go.sum
pkg/cloudclient/aws/private.go

The egress tests currently check if a connection can be established with a specified endpoint. However, with layer 7 packed inspection, the connection is allowed to establish but packets are still filtered. This causes the verifier to show egress urls as reachable when no data is able to pass in cases where layer 7 filtering is used. This PR changes the test to check the response instead of just the connection to more accurately reflect the reachability of the list of urls.
https://issues.redhat.com/browse/OSD-10903

Move to net/http connection test

---

Makefile

Making a new make target to be called by the new step in CI

OSD-9234 - Adding a new make target to validate formating

---

build/config/config.yaml

[OSD-9647](https://issues.redhat.com/browse/OSD-9647):
Done Criteria:
- Identify global AWS API endpoints with `us-east-1` in the URL
- Add global AWS API endpoints to the list of egress targets
Comment:
- The tagging service url  with `us-east-1` has already been removed from rosa in update, so we shouldn't need that. https://github.com/openshift/rosa/pull/547/commits/f49b5e7bf038df217886c2e46b7d768f3be44845
- I also added `route53domains.us-east-1.amazonaws.com` . That's the only service we might need that has a global URL . Reference: https://docs.aws.amazon.com/general/latest/gr/r53.html 
- I didn't find any global URLs used for IAM service.

osd-9647 added global urls for tagging and route53 domain service

---

pkg/cloudclient/aws/private.go
pkg/errors/errors.go
pkg/helpers/helpers.go

The purpose of this PR was to move the error definition which is mentioned in the helpers.go to errors.go file so, that we can throw a test time out error instead of generic(unhandled) error

OSD-11009: make test time out error pre-defined instead of generic

---

cmd/byovpc/cmd.go

As we added formatting checks in CI as part of [OSD-9234](https://issues.redhat.com/browse/OSD-9234) , we need to fix to formatting in order to unblock the CI.

OSD-9234 - Fixing formatting

---

build/Dockerfile

The entrypoint defined in the Dockerfile needs to be in the PATH to be able to behave properly.

OSD-11306 - Update dockerfile to have a working entrypoint 

---

OWNERS

While reviewing a PR, I noticed there was a dupp in the OWNERS entry so cleaning it up.

Removed dupp in OWNERS file

---

build/config/config.yaml

As part of the issues faced by in Prod when we activated osd-network-verifier, we found that the SFTP access was checked (and blocking is failed) while it is only Recommended in the docs. To align with docs, removing the check.
Reference : [OSD-11859](https://issues.redhat.com/browse/OSD-11859)
In addition, removing dupplicated check for quay-registry.s3.amazonaws.com

OSD-11859 - Removing SFTP as not Mandatory and removing dupplicated check

---

build/config/config.yaml

api.pagerduty.com is used only for service/account management, and not by the monitoring tools (which are using events.pagerduty.com) so removing it from the domains to be validated. 
Reference : [OSD-11912](https://issues.redhat.com/browse/OSD-11912)

OSD-11912 - Remove api.pagerduty.com from checked domains

---

pkg/cloudclient/aws/private.go

Updated to new Quay image after having removed port 22 test (https://github.com/openshift/osd-network-verifier/pull/117)
as the result of testing golangci gosec lint in osd-network-verifier repo: https://issues.redhat.com/browse/OSD-11465
Testing: make build the binary and tested the verifier with the new quay image. Success.

updated new quay image

---

build/bin/network-validator.go

added #nosec for InsecureSkipVerify to skip this check for the linter as a result of gosec :
test "/home/linnguye/golangci.yml" = "" || test ! -e "/home/linnguye/golangci.yml" || GOLANGCI_LINT_CACHE="/tmp/golangci-cache" golangci-lint run -c "/home/linnguye/golangci.yml" ./...
build/bin/network-validator.go:119:33: G402: TLS InsecureSkipVerify set true. (gosec)
TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
Justification: Low chance of MITM, as the instance is short-lived
related Jira card: https://issues.redhat.com/browse/OSD-11465

added // #nosec for InsecureSkipVerify

---

pkg/cloudclient/aws/private.go

The verifier currently gives an ambiguous error when a "generic" error happens. This PR adds two things to help clarify how to handle non-test failures:
1. Adds a check to see if the problem is specifically related to docker, and a specific message to indicate what went wrong. Error message is added to the print out.
2. Refines the generic error message to indicate that more investigation is needed as the egress test was not able to run fully.

Add more explicit error messages for generic errors and docker errors

---

README.md

Currently, the AWS and GCP docs return 404 as the filenames&folders are lowercase/
this PR updates the doc urls

docs: fix aws, gcp urls

---

.github/PULL_REQUEST_TEMPLATE.md

This adds a by-default PR template that should be welcoming users whenever they create a new PR
Ref: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

docs: add PR template for verifier

---

go.mod
pkg/cloudclient/aws/private.go
pkg/output/output.go

There is a desire to clearly identify errors associated with AWS calls so that permissions gaps could be easily identified. I chose to approach this by just annotating any errors those calls returned following the recommended approach for aws-sdk-go-v2: https://aws.github.io/aws-sdk-go-v2/docs/handling-errors/
Sample output:
```
❯ ./osd-network-verifier egress --subnet-id subnet-08cb0bad22281f031 --profile=onv                   
Using AWS profile: onv
Using region: us-east-2
Summary:
printing out errors faced during the execution:
-  network verifier error: missing required permission ec2:RunInstances
Failure!
```
```
❯ ./osd-network-verifier egress --subnet-id subnet-08cb0bad22281f031 --profile=onv --instance-type lol
Using AWS profile: onv
Using region: us-east-2
Unable to create AWS …
```

OSD-13005 Clearly associate errors with their AWS calls

---

pkg/cloudclient/aws/private.go

This updates the docker image to the latest as per the index: https://quay.io/repository/app-sre/osd-network-verifier?tab=tags&tag=latest 
The proxy can now be used as the following as it's enabled in the docker-image
```shell
./osd-network-verifier egress --subnet-id subnet-X  --http-proxy http://sre:x@1.2.3.4:8888 --https-proxy https://sre:x@1.2.3.4:8888  --cacert cert.pem --timeout 3s --debug  --profile your-aws-profile --region us-east-1
```

feat: enable proxy verification by bumping up the docker image

---

pkg/cloudclient/aws/private.go
pkg/cloudclient/aws/private_test.go
pkg/errors/errors.go
pkg/helpers/helpers.go
pkg/output/output.go

* Converted global vars to consts as we're not expecting to change their values at runtime
* Extended `NewGenericError` to handle aws-sdk-go-v2 errors to annotate `UnauthorizedException` errors so the code is DRY-er
* Updated `describeEC2Instances` to go off of the state name instead of the state code so it's easier to understand

OSD-13005 Generically handle aws-sdk-go-v2 errors

---

cmd/dns/cmd.go
cmd/egress/cmd.go
pkg/cloudclient/aws/private.go
pkg/errors/errors.go
pkg/helpers/helpers.go

* Independently check for `enableDnsHostnames` and `enableDnsSupport` and provide errors
* Recommend specifying an image-id when no default image is found
* We're only really aware of docker issues when parsing user data logs at the moment, but setting the code up to expand for future issues
* Consolidated `UnhandledError` (unused) and `EgressURLError` (used once) into `GenericError`
* Add support for the `--profile` flag to the dns subcommand
Sample output:
```
❯ ./osd-network-verifier dns --vpc-id vpc-09206ccf625ee370e --profile=onv
Using region: us-east-2
Using AWS profile: onv
Verifying DNS config for VPC vpc-09206ccf625ee370e
DNS Support for VPC vpc-09206ccf625ee370e: false
DNS Hostnames for VPC vpc-09206ccf625ee370e: true
Summary:
printing out exceptions preventing the verifier from …
```

OSD-13005 Improve debug logging and specificity of returned errors

---

Makefile
pkg/cloudclient/aws/aws.go
pkg/cloudclient/aws/private.go
pkg/cloudclient/aws/private_test.go
pkg/cloudclient/mocks/mock_aws.go
pkg/cloudclient/mocks/mock_cloudclient.go
pkg/errors/errors.go

* I separated applying tags out from the single `ec2:RunInstances` request so that we can give a specific error on a missing `ec2:CreateTags` permission which has the extra benefit of not requiring the end-user to guess which permission is missing. Since we are anticipating tag-based IAM policies, I made sure every time `createEC2Instance` is calls `ec2:RunInstances` and `ec2:CreateTags` in sequence so that this function can be used as-is.
* I also added a `make generate` Makefile target to run `mockgen` and validate it during PR checks

Break out `ec2:CreateTags` to simplify error handling logic

---

pkg/cloudclient/aws/private.go
pkg/helpers/config/userdata.yaml

In case it is not possible to pull the docker image from requested in osd-network-verifier, trying to default to the image prepulled (present in golden-ami)
To test the changes, I temporarily updated the docker image version in private.go to ensure the pull would fail.
```
$docker image ls --filter "reference=quay.io/app-sre/osd-network-verifier"
REPOSITORY                             TAG                IMAGE ID       CREATED       SIZE
quay.io/app-sre/osd-network-verifier   v0.1.33-5b7a940    4c6d898e60cc   6 days ago    103MB
quay.io/app-sre/osd-network-verifier   v0.1.212-5f88b83   e4d93a35c482   2 weeks ago   100MB
```
v0.1.33-5b7a940 is the version embedded in the current AMI, v0.1.212-5f88b83 is the current version requested by osd-network-verifier
With default image
```
USERDATA …
```

Defaulting to prepulled docker image

---

cmd/dns/cmd.go
cmd/egress/cmd.go
pkg/cloudclient/aws/aws.go
pkg/cloudclient/aws/private.go
pkg/cloudclient/cloudclient.go
pkg/output/output.go

The output now looks something like this when using the `--debug` flag. It looks the same as before without the debug flag.
```
Summary:
printing out debug logs from the execution:
-  Gathering description of instance type t3.micro from EC2
-  Using configured timeout of 2s for each egress request
-  base64-encoded generated userdata script:
---
${b64UserData}
---
-  Using AMI: ami-09d6a8053437e16bf
-  Waiting for EC2 instance i-0cbce467076c2637d to be running
-  Describing state of EC2 instance i-0cbce467076c2637d
-  Instance i-0cbce467076c2637d has no status yet
-  Describing state of EC2 instance i-0cbce467076c2637d
-  Scraping console output and waiting for user data script to complete...
-  EC2 console consoleOutput contains data, but end of userdata script not seen, continuing to …
```

OSD-13241 Add debug logs to output struct

---

cmd/egress/cmd.go
examples/aws/proxy_enabled.go
examples/aws/verify_egressv1.go
examples/aws/verify_egressv2.go
pkg/cloudclient/aws/aws.go
pkg/cloudclient/aws/private.go
pkg/cloudclient/aws/private_test.go
pkg/cloudclient/cloudclient.go
pkg/cloudclient/gcp/gcp.go
pkg/cloudclient/gcp/gcp_test.go
pkg/cloudclient/mocks/mock_cloudclient.go

Added a `--security-group-id` flag so that a specific one can be specified on the CLI.
e.g.
```bash
./osd-network-verifier egress --subnet-id subnet-010292f1964143c8d --security-group-id sg-0ebcec4462fe7e5b7 --profile=onv 
Using AWS profile: onv
Using region: us-east-2
Created instance with ID: i-0aa70edb273d93dd2
EC2 Instance: i-0aa70edb273d93dd2 Running
Terminating ec2 instance with id i-0aa70edb273d93dd2
Summary:
All tests pass!
Success
```

OSD-12354 Add --security-group-id flag to specify one for the ONV EC2 Instance

---

cmd/egress/cmd.go

On-call ran into this issue: 
`fix for network verifier error: error performing ec2:CreateTags: For 'Name', use the capitalization specified by the tag policy.`
This is due to an AWS tag policy specified by the customer (https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_example-tag-policies.html), but we should use the correct capitalization anyway.

Bugfix - correct name tag capitalization

---

integration/pkg/aws/cleanup.go

While running this integration test in all regions for [OSD-13240](https://issues.redhat.com//browse/OSD-13240) to validate the custom AMI, sometimes the firewall took more than 10 minutes to delete, so bumping to 20 minutes.

Sometimes the firewall can take more than 10 minutes to delete

---

README.md
RELEASE.md

This outlines the ad-hoc testing that we have been doing to validate PRs ahead of creating a versioned release of `osd-network-verifier` for [OSD-12359](https://issues.redhat.com//browse/OSD-12359). Hopefully it will be automated one day!

OSD-12359 Add MVP RELEASE.md

---

docs/aws/aws.md
pkg/clients/aws/aws.go
pkg/verifier/aws/aws_verifier.go
pkg/verifier/aws/entry_point.go

This implements [OSD-13305](https://issues.redhat.com//browse/OSD-13305) to switch away from our custom waiters to the AWS SDK provided ones to break apart the changes in #145 
Validated:
* A functional VPC in AWS us-east-2
* The integration test still works in AWS us-east-2

Switch to using AWS SDK provided waiters

---

pkg/verifier/aws/aws_verifier.go

Creates `GetAMIForRegion` so external code bases can use the AMI IDs. 
Ref: https://issues.redhat.com/browse/OSD-13537
This unblocks https://issues.redhat.com/browse/SDA-6178

Allow default AMI map to be accessable by library consumers

---

pkg/helpers/config/userdata.yaml
pkg/verifier/aws/aws_verifier.go

This PR ensures that no EC2 instances are accidentally left behind by the verifier post-egress-check. To this end, `createEC2Instance()` has been modified to set the [_InstanceInitiatedShutdownBehavior_](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-ec2.InstanceInitiatedShutdownBehavior.html) attribute to `TERMINATE` on any verifier-created instances, meaning that EC2 will automatically terminate an instance when it shuts itself down (e.g., by running the `poweroff` shell command). Additionally, a [`power_state`](https://cloudinit.readthedocs.io/en/latest/topics/modules.html#power-state-change) directive has been added to the userdata template instructing cloud-config to power-off the instance either 5 minutes after the validator binary completes or 10 minutes after boot …

Self-destructing EC2 instances

---

dashboards/grafana-dashboard-network-verifier.configmap.yaml

Feature
Following conversations with app-sre team it was suggested to create this file in order to set here the dashboards for the osd-network-verifier.  Thread https://coreos.slack.com/archives/CCRND57FW/p1667831061874529
Related issue OSD=13207
The PR contains a generated configmap that holds the promQL code for dashboards and queries that are run to create the dashboard in

OSD-13207 adding grafana dashboard for osd-network-verifier

---

pkg/helpers/config/userdata.yaml

Fix: https://issues.redhat.com/browse/OSD-13937
Enables the `https` if the `https proxy` is passed as transparent proxy (when there's no ca)
Testing: it can be tested against the cluster in the ticket
```shell
./osd-network-verifier egress --subnet-id subnet-xx --security-group-id sg-xxx --http-proxy "http://lookup-from-cluster:3128" --https-proxy "http://lookup-from-cluster:3128" --region eu-west-2
```

fix: pass https proxy if provided even when there's no ca

---

cmd/egress/cmd.go

This closes OSD-12772. Added flag to pass vpc-name for the gcp workflow
I added a flag to the egress command to pass the optional "vpc-name" flag explaining this will be part of the GCP workflow (checked only when the --gcp=true flag is set). In addition I left the other option of also having the env var GCP-VPC-NAME flag set so it can be one or the other.

Enhancement: This closes OSD-12772. Added flag to pass vpc-name for the gcp workflow

---

pkg/clients/aws/aws.go
pkg/verifier/aws/aws_verifier.go

For [OSD-14143](https://issues.redhat.com//browse/OSD-14143):
Adding a new helper function so consumers can just pass in their own AWS client/logger and not depend on network-verifier's opinionated workflow for assembling them. This will be useful in cases like osdctl and other consumers

Add additional helper function for setting up AwsVerifier

---

go.mod
main.go

Type: Clean-up
This removes flag initialization that's performed during startup, as it's being checked by cobra already
Testing:
Check the output (against the previous version), you shouldn't be seeing any diff

cleanup: remove unnecessary flag initialization

---

Makefile
boilerplate/openshift/golang-lint/ensure.sh
boilerplate/openshift/golang-lint/golangci.yml

Just a plain `make boilerplate-update` to get this repo up-to-date. This should enable https://github.com/openshift/release/pull/35788 to pass, which will allow getting this repo updated to Go 1.19

make boilerplate-update

---

.ci-operator.yaml
go.mod
go.sum

The culmination of efforts starting with #166 - no other dependency updates

Update osd-network-verifier to Go 1.19

---

pkg/verifier/aws/aws_verifier.go

This moves the step of creating tags into the same step that creates the EC2 instance and EBS volumes. This is required for the move to tag-based permission enforcement. Without this, instance will not be able to be created since the tags are required at creation time.

Move the tag creation to happen at instance creation time.

---

pkg/clients/aws/aws.go
pkg/verifier/aws/aws_verifier.go

Similar to #169 
This moves the step of creating tags into the same step that creates the Security Group. This is required for the move to tag-based permission enforcement. Without this, the Security Group will not be able to be created since the tags are required at creation time.

Move Security Group tag creation to be part of the Security Group creation

---

integration/main.go
pkg/errors/errors.go
pkg/errors/errors_test.go
pkg/output/output.go
pkg/output/output_test.go
pkg/verifier/aws/aws_verifier.go
pkg/verifier/aws/aws_verifier_test.go

This PR is a iteration in the vein of [OSD-15078](https://issues.redhat.com//browse/OSD-15078)
Currently, it is difficult for consuming repos to determine exactly
which egress URLs are blocked without manually doing regex parsing on an
array of failure strings that we return. This commit solves this by
adding an egressURL field with EgressURL() and GetEgressURLFailures()
methods so that consuming repos can more easily obtain this information.
I updated the integration test so that it would print out the egress failures using the new functionality in this PR. Just running it should replicate my results.
The results of me adding this code block to the integration test (which only blocks quay.io:443)
```go
for _, ef := range egressFailures {
log.Printf("egress failure: %s", ef.EgressURL())
} …
```

Allow consuming repos to obtain all URLs associated with egress failures

---

cmd/egress/cmd.go
pkg/helpers/config/userdata.yaml
pkg/verifier/aws/entry_point.go
pkg/verifier/package_verifier.go

Feature:
This PR adds a Parameter (--skip-termination) to be able to leave the debug instance running for further debugging. 
This PR also adds the (--terminate-debug) that will terminate the debug instance that was left running.

Feature: Add Skip-termination Command to keep debug instance up

---

pkg/verifier/aws/entry_point.go

Bug fix for [OSD-16076](https://issues.redhat.com//browse/OSD-16076)
In case we got an error and we couldn't create the EC2 instance, we should still clean the SG up in case we created one so skipping the log analysis and the TerminateInstace but continuing the function to cleanup the SG. 
This is only a first part of the fix (even though it should be the most common case we are facing) - we still need to better handle the error case inside the 'CreateSecurityGroup' function itself.

Ensuring the SG cleanup in case of error when creating the instance

---

pkg/output/output.go

Related issue: https://issues.redhat.com/browse/SDA-6670
Adds a formatted string output from logs instead of directly printing to stdout, clients can consume the raw string
Clients currently have no access to the debug logs

SDA-6670 | feat: add formating function to retrieve output logs

---

integration/main.go
integration/pkg/aws/setup.go
pkg/helpers/config/userdata.yaml

Fixes a bug when osd-network-verifier times out due to being unable to `docker pull`, even when it is not necessary
```bash
IMAGE=`docker images ${VALIDATOR_REPO} -q  | head -n 2 | tail -n 1`
if [[ -n "${IMAGE}" ]]; then # should be -z for if $IMAGE is empty
sudo docker pull ${VALIDATOR_IMAGE} >> /var/log/userdata-output
```
Also some improvements to the integration test, sometimes the test errors because the VPC can take a bit to initialize and cleaned up the help menu.
[OSD-16322](https://issues.redhat.com//browse/OSD-16322)
Original integration test help menu:
```
❯ ./integration -h                            
Usage of ./integration:
-alsologtostderr
log to standard error as well as files
-create-only
When specified, only create infrastructure and do not delete
-delete-only
When …
```

Fix bash error causing osd-network-verifier timeouts pulling from quay.io

---

RELEASE.md
integration/main.go
pkg/verifier/aws/entry_point.go

Enhancement
[OSD-16065](https://issues.redhat.com//browse/OSD-16065)
While working on https://github.com/openshift/osdctl/pull/390 I learned that it would have been nice if:
* Part of the release process did a quick sanity check on the required egresses for the `hostedcluster` PlatformType as well, so I updated the integration test to allow passing in a `--platform`.
* There was a debug log to indicate which config file a run was using.
With this logging change and pulling it into osdctl as an example it could look like this:
```
❯ ~/git/openshift/osdctl/osdctl network verify-egress --cluster-id mshen-hyper --subnet-id subnet-05a1fa90715fd0cc3 -S
2023/05/31 21:47:31 getting AWS credentials from backplane-api
2023/05/31 21:47:32 using platform: hostedcluster
2023/05/31 21:47:32 using …
```

Add release step to check the hostedcluster platform type

---

pkg/verifier/aws/aws_verifier.go
pkg/verifier/aws/aws_verifier_test.go

- Bug
We found a case where the size of the trust bundle caused the length of user-data to exceed its maximum of 16384 bytes, this PR is to return a clear and specific error in case of unsupported length so that we can ensure not block install wrongfully and fail fast. 
Jira: [OSD-15282](https://issues.redhat.com/browse/OSD-15282)
```
$ ./osd-network-verifier egress --platform aws --subnet-id subnet-0a3e18468e9495462 --security-group-id sg-0e0bec2444c1282f9 --profile default --region us-east-1                                                                                                       1 ↵
Created instance with ID: i-05979e1b00a73face
Summary:
... omitted ...
```
```
$ ./osd-network-verifier egress --platform aws --subnet-id …
```

OSD-15282 osd-network-verifier with lengthy trust bundles

---

pkg/verifier/aws/aws_verifier.go

This update the AMIs and verifier image to support eu-central-2.
Reference:
* https://ci.int.devshift.net/job/gl-build-master-osd-network-verifier-golden-ami-packer/49/consoleFull
* https://quay.io/repository/app-sre/osd-network-verifier/manifest/sha256:55d74f02bc46673d9d0f7f1511a3fd4be2e5cf0a773501a23a87b85dd8ab233f

[SDE-2273] Update AMIs and verifier image to support eu-central-2

---

pkg/verifier/aws/aws_verifier.go

Adds eu-south-2 AMI and quay.io sha
Ref:
https://ci.int.devshift.net/job/gl-build-master-osd-network-verifier-golden-ami-packer/50/consoleFull
https://quay.io/repository/app-sre/osd-network-verifier/manifest/sha256:cb0822c72cd970675d79a58e1c3fbe2d6e703f6417fc3fdf961664800030ac73

[SDE-2272] Add eu-south-2 AMI and latest quya.io sha

---

cmd/egress/cmd.go
pkg/verifier/aws/aws_verifier.go
pkg/verifier/aws/aws_verifier_test.go
pkg/verifier/aws/entry_point.go

This PR addresses [OSD-19401](https://issues.redhat.com/browse/OSD-19401), which identifies a bug/feature gap in the AWS security groups auto-generated by osd-network-verifier (i.e., when the caller does not supply a sec. group ID). Currently, these security groups are created with a static set of rules allowing egress to TCP ports specified in the egress list (e.g., 80, 443). If the user is testing a network with a proxy configuration, this static rule set might not allow traffic to flow to the user's proxy server running on, e.g., port 8080.
This PR extends the verifier's sec. group auto-generation logic such that it adds egress rules to the base set that cover the ports used in the user-provided proxy URLs. For example, if a user passes the arguments `--http-proxy …

Add rules allowing proxy traffic to auto-generated security group

---

cmd/egress/cmd.go
docs/aws/aws.md
examples/aws/verify_egress.go
pkg/verifier/aws/aws_verifier.go
pkg/verifier/aws/entry_point.go
pkg/verifier/package_verifier.go

This PR addresses bug [OSD-19998](https://issues.redhat.com/browse/OSD-19998), which reported security group (SG) leakage in certain code paths involving automatic SG creation. In summary, if an AWS API error was encountered between the creation of the SG and the creation of the EC2 instance, the network-verifier would exit/return without cleaning up it's auto-generated SG. This is fixed by calling `defer CleanupSecurityGroup()` earlier in the code, ensuring that the SG cleanup function is run in almost all cases. This PR also performs some general code cleanup, including clearer documentation of the deprecation of the `--security-group-id`/`securityGroupId` parameter and making the use of its successor, `--security-group-ids`/`SecurityGroupIDs`, more consistent across the codebase.
Note …

Address security group leak with earlier `defer` call

---

pkg/helpers/helpers.go
pkg/helpers/helpers_test.go
pkg/verifier/aws/aws_verifier.go
pkg/verifier/aws/aws_verifier_test.go

This PR addresses a bug in #202's implementation of [OSD-19401](https://issues.redhat.com/browse/OSD-19401). The original implementation did not check for equality between the HTTP and HTTPS proxy URLs passed by the user/caller, leading `AllowSecurityGroupProxyEgress()` to generate duplicate security rules that get rejected by the AWS API. This bugfix adds set-like behavior where new security group rules are checked against existing ones before being added to the AuthorizeSecurityGroupEgress AWS API call.
1. Set up a test VPC that forces internet access through a basic HTTP proxy (Squid worked well for me) that runs on ports other than 80, 443, or 9997
2. Checkout this PR, `cd` into the root of the repo, and run `make test` and `make build`
3. Run the verifier, specifying **two equivalent …

Check for duplicates before adding proxy sec. group rules

---

pkg/verifier/aws/entry_point.go

fix a bug introduced where the describe security Group  filters were built with empty value for VpcID
make sure the VpcId always has a value. extracted from the if that executed only when we dont use a --security-group-id flag. Now we always have the VpcId which we need in other parts of the code.

fix a bug introduced with the describe security Group  filters

---

OWNERS

This PR updates OWNERS such that it aligns with the recent team re-org. I've set `reviewers` ~= Team Aurora. I've also moved `approvers` no longer involved with the project to [`emeritus_approvers`](https://www.kubernetes.dev/docs/guide/owners/#emeritus). Finally, I added myself and Raf as `approvers`, and set the symbolic `maintainers` to myself and fahlmant.
Open to feedback 😃

Align OWNERS with re-org

---

.gitignore
README.md
examples/aws/terraform/vpc-firewall/README.md
examples/aws/terraform/vpc-firewall/main.tf
examples/aws/terraform/vpc-firewall/terraform.tfvars.example
examples/aws/terraform/vpc-firewall/variables.tf
examples/aws/terraform/vpc/README.md
examples/aws/terraform/vpc/main.tf
examples/aws/terraform/vpc/terraform.tfvars.example
examples/aws/terraform/vpc/variables.tf

Use Terraform IaC to provide an alternative way to quick establish a VPC with or without a firewall for osd-network-verifier testing.
This Terraform script sets up a network infrastructure in the AWS Cloud. The infrastructure includes a Virtual Private Cloud (VPC), subnets, a network firewall(optional), and an Internet Gateway.
1. **VPC:** The script creates a VPC in the specified AWS region. 
2. **Subnets:** Three subnets are created within the VPC - a public subnet, a private subnet, and a firewall subnet. Each subnet is created in the specified availability zone with its respective CIDR block.
3. **Internet Gateway:** An Internet Gateway is created and attached to the VPC. This allows the VPC to communicate with the Internet.
4. **Network Firewall(optional):** A …

Add terraform IaC for osd-network-verifier example/quick testing

---

RELEASE.md
pkg/verifier/aws/aws_verifier.go

Updates docs around releasing and also fixes a bug with resource cleanup in integration tests.
Error I was seeing from cleanup:
```
panic: operation error EC2: DeleteVpc, https response error StatusCode: 400, RequestID: 3ee80c4a-badb-415a-9b95-f568cf795270, api error DependencyViolation: The vpc 'vpc-0fa551f9b466b36a6' has dependencies and cannot be deleted.
```
When I went and looked at the VPC in AWS, there was still a security group attached.

Update release process docs and AMI images

---

integration/pkg/aws/aws.go
integration/pkg/aws/cleanup.go
integration/pkg/aws/ec2.go

During resource cleanup, integration tests fail to delete a VPC if there are dangling security groups attached. This change will make sure that those security groups are
These logs used to appear during cleanup:
```
panic: operation error EC2: DeleteVpc, https response error StatusCode: 400, RequestID: 3ee80c4a-badb-415a-9b95-f568cf795270, api error DependencyViolation: The vpc 'vpc-0fa551f9b466b36a6' has dependencies and cannot be deleted.
```
This change will fix that error.

Cleanup security groups during integration test cleanup

---

pkg/verifier/aws/aws_verifier.go

https://issues.redhat.com/browse/OSD-20983
Enables instance Metadata service v2 on the ec2 instance created by the network verifier. The IMDSv2 introduces session-oriented requests, which adds defense in depth against unauthorized metadata access. This will not make big change on the network verifier instance at the moment since we do not request any metadata about the instance. But if at some point we do we can just call the same IMDSv1  IP url for it but now with an authentication token.

enabled IMDSv2 service for the network verifier instance

---

cmd/egress/cmd.go
pkg/verifier/aws/aws_verifier.go
pkg/verifier/aws/entry_point.go
pkg/verifier/package_verifier.go

#type of change
https://issues.redhat.com/browse/OSD-20969
Added a --force-temp-security-group flag that will force the creation of a security group to attach to the instance whenever this flag is passed (whether we pass with flags other security groups or not).
Run network verifier with the following flags
1 ) "--force-temp-security-group " and "--security-group-id" (expected 2 SGs to be attached to instance, the temp and the passed. The created one to be cleaned at the end).).
2) "--force-temp-security-group " and "--security-group-ids" (expected all SGs passed and the newly created one to be attached to instance, and the created one to be cleaned at the end).
3) if all the 3 flags are passed an error since the security-group-id and security-group-ids flags are are …

added --force-temp-security-group flag

---

RELEASE.md
cmd/egress/cmd.go
docs/aws/aws.md
docs/gcp/gcp.md
pkg/helpers/helpers.go
pkg/helpers/helpers_test.go

- Refactoring
https://issues.redhat.com/browse/OSD-20380
Deprecates platform type names "aws", "hostedcluster", and "gcp" in favor of "aws-classic", "aws-hcp", and "gcp-classic" respectively.
1. Set up an AWS account configured with a VPC, firewall, or other components you wish to verify.
- can be accomplished by running the `./integration` binary in `--create-only` mode.
2. run `make build` from the project's root directory
3. run `./network-verifier egress --platform rosa-classic --subnet-id <public subnet ID> --security-group-ids <security group associated to VPC> --profile <your aws profile>` and note your results.
4. run `./network-verifier egress --platform aws--subnet-id <public subnet ID> --security-group-ids <security group associated to VPC> --profile <your aws profile>` and …

Update platform type names

---

integration/main.go
pkg/helpers/config/userdata.yaml
pkg/verifier/aws/aws_verifier.go
pkg/verifier/aws/entry_point.go

This PR updates the default AMI IDs and Quay image IDs to their latest values per our [release documentation](https://github.com/openshift/osd-network-verifier/blob/main/RELEASE.md). AMI IDs were pulled from [Jenkins build 58](https://ci.int.devshift.net/job/gl-build-master-osd-network-verifier-golden-ami-packer/58/console).
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- ~~[ ] I have added execution results to the PR's readme~~
I suggest running `make build`, `make test`, and integration tests for both "aws-classic" and  "aws-hcp" platform types. While the integration tests are running, ensure recently-added features (e.g., IMDSv2, no redirect following) are working as intended.

Bump AMI/image IDs and fix bugs in preparation for next release

---

pkg/verifier/aws/aws_verifier.go

-Release
What does this PR do?
Bump golden ami ids for next release of the network verifier
Bump the ami and ran integration tests according to SOP.

Bump golden ami ids for next release of the network verifier

---

pkg/verifier/aws/aws_verifier.go

fixing double sha25 typo

---

Makefile
cmd/root.go
version/version.go

Adds version information on build that can be accessed via `--debug` and `--version` flags. _These will only be available when directly running a built binary of network verifier_.
```
$ ./osd-network-verifier --version                 
osd-network-verifier version v0.4.11@46fefcb
$ ./osd-network-verifier --debug
Version:        v0.4.11
Commit Hash:    46fefcbfcc7a5b4c64595f6711af6a5ce2d1211f
...
```

Add version info on build

---

pkg/helpers/helpers.go
pkg/helpers/helpers_test.go
pkg/probes/curl_json/curl_json.go
pkg/probes/curl_json/curl_json_test.go
pkg/probes/curl_json/userdata-template.yaml

This PR is composed of commits cherry-picked from my larger [OSD-22892](https://issues.redhat.com/browse/OSD-22892) branch for the sake of readability.
These commits improve CurlJSONProbe's ability to validate input variables and "render" special userdata template variables. For example, the verifier's existing critical path sets duration-as-a-string values  (e.g., "1m3s" for 63 seconds) for the the `TIMEOUT` and `DELAY` userdata variables. Curl's `--max-time ${TIMEOUT}` flag doesn't accept such non-numeric values, so we've added a function called `normalizeSaneNonzeroDuration()` that converts durations-as-strings into floating-point quantities of seconds, does some sanity checking (i.e., 0 < `TIMEOUT` < 3hrs), and returns a curl-safe float-as-a-string (or, in the case of `DELAY`, a …

OSD-22892 (Part 3): CurlJSONProbe Improvements

---

cmd/egress/cmd.go
pkg/verifier/aws/aws_verifier.go
pkg/verifier/aws/entry_point.go
pkg/verifier/package_verifier.go

Removes deprecated `securityGroupId` property from `createEc2InstanceInput` struct.
Depends on PRs to the three known downstream consumers to stop using the field:
osdctl: https://github.com/openshift/osdctl/pull/592 (merged)
CAD: https://github.com/openshift/configuration-anomaly-detection/pull/300 (merged)
CS: No uses detected

Remove deprecated 'securityGroupId' property from createEC2InstanceInput

---

cleangoldenami/README.md
cleangoldenami/go.mod
cleangoldenami/main.go
cleangoldenami/main_test.go

Cleanup script makes sure to delete the oldest image of each type per region, not just the oldest image
```
./cleangoldenami --dry-run --verbose                                                                                                                                                                                                                                                                                         
Region us-east-1 is under quota. (Images: 15, Quota: 20)
Region ca-central-1 image capacity is currently at 18 out of 20 - would delete the following AMIs:
- ami-085e5999c054f7443 (legacy-x86_64)
Region us-east-2 image capacity is currently at 20 out of 20 - would delete the following AMIs:
- ami-06c3c5a8d32a87309 (legacy-x86_64)
- ami-0241f2d4397f1cade (legacy-x86_64)
- …
```

[OSD-24207] Updated logic to delete oldest image of each type per region

---

cmd/egress/cmd.go
pkg/probes/curl/curl_json.go
pkg/probes/curl/curl_json_test.go
pkg/probes/legacy/legacy.go
pkg/probes/legacy/legacy_test.go
pkg/verifier/aws/entry_point.go
pkg/verifier/package_verifier.go

This PR changes the way we're setting the default values of certain probe parameters (e.g., per-request timeout) such that users of the `osd-network-verifier` CLI will get an experience that's more consistent with consumers of the API (e.g., OCM). The only concrete change to defaults is the increase of the per-request timeout from 2s to 5s.
This PR also improves probe outputs by replacing "telnet" with "tcp" (since "telnet" is just an implementation detail and might confuse customers) and improves AMI selection with support for the HCP platform type.
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
Checkout this PR, run `make test build`, and then play around with `./osd-network-verifier` like you normally would. To test the specific behaviors changed …

Standardize how we set defaults and clarify egressURL output

---

cmd/egress/cmd.go
go.mod
go.sum
integration/go.mod
pkg/data/egress_lists/egress_lists.go
pkg/verifier/aws/entry_point.go

[OSD-22628](https://issues.redhat.com//browse/OSD-22628)
Fetch the URL list from github first. Fall back to the local list (current behavior) if that fails, i.e. github is down.
Pull this commit down and run it exactly as you normally would. You should see a `Using egress URL list from...` line in the console output if the new list is being used.
The file blob can be viewed with https://api.github.com/repos/openshift/osd-network-verifier/git/blobs/<file_sha>
```
./osd-network-verifier egress --subnet-id subnet-0ca196afecc8548bb --security-group-ids sg-041c0bed52e968857
Using egress URL list from https://api.github.com/repos/openshift/osd-network-verifier/contents/pkg/data/egress_lists/aws-classic.yaml?ref=main at SHA …
```

Fetch url list from github first before falling back to local

---

pkg/data/egress_lists/egress_lists.go

I committed this in https://github.com/openshift/osd-network-verifier/pull/254 and then never pushed it up 🤦🏻 
```
...
Using egress URL list from https://api.github.com/repos/openshift/osd-network-verifier/contents/pkg/data/egress_lists/aws-classic.yaml?ref=main at SHA 5fd26419a0a6529a2a692fee0abe591d58542ec3
...
```

add '.yaml' to end of github path

---

cmd/egress/cmd.go
pkg/data/egress_lists/egress_lists.go
pkg/verifier/aws/entry_point.go
pkg/verifier/package_verifier.go

Adds a new flag to allow a user to pass a specific egress URL list.
Resolves [OSD-22629](https://issues.redhat.com//browse/OSD-22629)
To test locally - simply run the verifier as usual but pass in `--egress-list-location` with either an external url or a local file path (absolute or relative to the working directory).

Add a flag to provide a custom location for the egress URL list

---

pkg/clients/aws/aws.go
pkg/verifier/aws/aws_verifier.go

This PR speeds up `ValidateEgress()` but adjusting how often we're checking for serial console output (i.e., "the `PollImmediate()` loop") and if the EC2 instance has finished terminating. This means that we'll spend less time unnecessarily waiting if, e.g., an instance finishes terminating after 17 seconds, as the previous config would only have checked once at 15s and again at 30s, whereas this new config will check at 3s, 6s, 9s... 15s, and 18s. 
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- ~~[ ] I have added execution results to the PR's readme~~
Keep an eye out for previously unforeseen race conditions …

Tune polling intervals for an overall faster `ValidateEgress()`

---

pkg/data/cloud/platform.go
pkg/data/cloud/platform_test.go

This extends the Platform structs to accept `aws-hosted-cp` as a valid value for looking up AWSHCP `ByName()`. This value is used internally still and blocks integrating the updated verifier.

OSD-25868: Adds `aws-hosted-cp` as a valid Platform name

---

README.md
examples/aws/terraform/vpc-proxied-explicit/README.md
examples/aws/terraform/vpc-proxied-explicit/assets/Caddyfile.tpl
examples/aws/terraform/vpc-proxied-explicit/assets/mitmproxy-sysctl.conf
examples/aws/terraform/vpc-proxied-explicit/assets/mitmproxy.service
examples/aws/terraform/vpc-proxied-explicit/assets/userdata.yaml.tpl
examples/aws/terraform/vpc-proxied-explicit/main.tf
examples/aws/terraform/vpc-proxied-explicit/terraform.tfvars.example
examples/aws/terraform/vpc-proxied-explicit/variables.tf
examples/aws/terraform/vpc-proxied-transparent/README.md
examples/aws/terraform/vpc-proxied-transparent/assets/Caddyfile.tpl
examples/aws/terraform/vpc-proxied-transparent/assets/mitmproxy-sysctl.conf
examples/aws/terraform/vpc-proxied-transparent/assets/mitmproxy.service
examples/aws/terraform/vpc-proxied-transparent/assets/userdata.yaml.tpl
examples/aws/terraform/vpc-proxied-transparent/main.tf
examples/aws/terraform/vpc-proxied-transparent/terraform.tfvars.example
examples/aws/terraform/vpc-proxied-transparent/variables.tf

This PR supersedes #267 and implements [OSD-23854](https://issues.redhat.com/browse/OSD-23854), which calls for the code from [abyrne55/transparent-proxy-setup](https://github.com/abyrne55/transparent-proxy-setup) to be moved into this repo's "example" code directory. The two directories created by this PR (vpc-proxied-explicit and vpc-proxied-transparent) contain Terraform scripts for quickly deploying AWS VPCs that explicitly- or transparently-proxy their traffic through a generated proxy server. 
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- ~~[ ] I have tested the functionality against gcp / aws, it doesn't cause any regression~~
Please read through and run through …

Add transparant and explicit proxy terraform scripts

---

pkg/probes/curl/curl_json.go
pkg/verifier/aws/entry_point.go

update the comments for the ensurePrivate flag

---

pkg/data/egress_lists/aws-classic.yaml
pkg/data/egress_lists/aws-hcp.yaml
pkg/data/egress_lists/gcp-classic.yaml

Addresses [OSD-25930](https://issues.redhat.com/browse/OSD-25930) by correcting removed endpoints
Standard testing process for network verifier. No special instructions.
N/A

OSD-25930: Corrects endpoint mistake

---

pkg/verifier/gcp/entry_point.go

Fix a bug from the previous Platform work that defaulted GCP to the wrong Platform.

Fix default PlatformType in GCP entrypoint

---

pkg/verifier/aws/entry_point.go
pkg/verifier/gcp/entry_point.go

The `--egress-list-location` flag provided by the CLI was being ignored in the parsing logic that constructs URLS from given input YAML. This primarily ensures that if the `ValidateEgressInput` has a populated `EgressListYaml` value, we parse it and use it. I also moved the flow control around a bit for the decision making about where to source the data from to make it a bit easier to follow.
I wanted to refactor this further and consolidate the behavior between both AWS and GCP, but opted to tackle that in a follow on so it was easier to review the bug in isolation.
I ran this locally with the CLI to confirm it works with and without an `--egress-list-location` flag:
**With**
```
> ./osd-network-verifier egress --profile devaccount --subnet-id subnet-0bab965a3722b750d --no-proxy …
```

OSD-25966: Fix issue with `--egress-list-location` CLI flag

---

pkg/data/egress_lists/egress_lists.go
pkg/data/egress_lists/egress_lists_test.go
pkg/verifier/aws/aws_verifier.go
pkg/verifier/aws/entry_point.go
pkg/verifier/gcp/entry_point.go
pkg/verifier/gcp/gcp_verifier.go

When working on a bugfix in https://github.com/openshift/osd-network-verifier/pull/282, I wanted to consolidate duplicate code and clean up the control flow further for generating egress lists. This PR does just that, by first extracting the existing behavior into a common type, and adding tests for the various scenarios. A couple of notes:
* I did not add validation for invalid `PlatformType` as was setup before, since the caller should be using the various exported `vars` for `PlatformType` and not manually constructing there own alias type with custom `name` values.
* Opted for a small interface to abstract the GitHub API call to fetch contents
* Moved the various Getters in `egress_lists` to function receivers on the `Generator` struct. These functions are not used anywhere in the …

OSD-26330: Refactor and add tests for `egress_lists` package

---

cmd/egress/cmd.go
pkg/data/cpu/cpu.go

added ArchitechtureByName() function check after normalization in order to account for an architecture with less than 3 names in the future. Also added better --notls and --cacert flags as mutually exclusive
- Bug
- Enhancement

OSD-26102 added architechturebyname check

---

OWNERS

Removing michael shen from OWNER FILE as part of the leaver process

OSD-26236 leaver process member removal

---

pkg/errors/errors.go
pkg/verifier/aws/aws_verifier.go

Added code to allow network verifier to highlight issues when instance changes state to termination due to issues with KMS
Solves https://issues.redhat.com/browse/OSD-21895

osd-21895 network verifier highlights kms permission issues

---

pkg/data/egress_lists/aws-classic.yaml
pkg/data/egress_lists/egress_lists_test.go

This PR removed the servicequota.$REGION.amazonaws.com URL from the OSD/ROSA Classic egress URL list, as that URL has been deemed unnecessary and is about to be removed from the docs (see openshift/openshift-docs#77271)

Remove servicequota URL from aws-classic.yaml

---

pkg/verifier/aws/aws_verifier.go

allow custom dns query

---

pkg/probes/curl/systemd-template.sh

This PR fixes OSD-27707, which identified a bug in how we were passing the `http_proxy` and related environmental variables to the systemd-based curl probe. Using the `Environment` systemd directive ensures the variables are properly set

Properly set proxy env vars in systemd curl probe

---

pkg/verifier/aws/aws_verifier_test.go
pkg/verifier/aws/entry_point.go
pkg/verifier/gcp/entry_point.go
pkg/verifier/gcp/gcp_verifier.go
pkg/verifier/package_verifier.go

This consolidates the default timeout into a shared constant. I noticed these were set individually when checking on what it was.
Also fixed a couple linting failures, which means I need to figure out why these aren't caught/showing up in CI..

Consolidate the default timeout, lint

---

RELEASE.md

This PR rewrites the releasing documentation (RELEASE.md) to better reflect current practices. This doc should also make it easier for maintainers to identify parts of the release process that could be better automated. In the meantime, this doc introduces some partial automation in the form of BASH snippets. Notably, this doc also formalizes the requirement that we enable deregistration protection on each AMI that's referenced in a released version.

Rewrite releasing doc

---

pkg/data/curlgen/curlgen.go
pkg/data/curlgen/curlgen_test.go
pkg/probes/curl/curl_json.go
pkg/probes/curl/curl_json_test.go
pkg/probes/curl/systemd-template.sh
pkg/probes/curl/userdata-template.yaml
pkg/verifier/aws/entry_point.go

- Refactoring
Centralize the logic/template that we use to generate curl commands in the network verifier such that there are not multiple pieces of the codebase that need to be updated each time we need to make a change to the curl command.
Changed the instances in which we use the flag "-k" for its more readable equivalent "--insecure"
Exports the building of the Curl command used in the network verifier curl probe. into it's own package.

SREP-597: Export curl command building to another package

---

pkg/clients/kube/kube.go
pkg/verifier/kube/kube_verifier.go

When the verifier Job fails to schedule a Pod due to `ImagePullBackoff`, the watcher would hang indefinitely until you exited.
This was primarily due to the `FailureTarget` status that shows up in the slice of status conditions. We need to detect this as a possible failure mode as well, since it shows up first.
I also lowered the deadline to 3min, since we really expect this Pod to complete quickly.
I tested this by using a bogus image.
```
 ./osd-network-verifier egress --pod-mode --region us-east-1
Using egress URL list from https://api.github.com/repos/openshift/osd-network-verifier/contents/pkg/data/egress_lists/aws-classic.yaml?ref=main at SHA 997186fa8fbf863db4b071d246e7bb781bc1e796
Summary:
printing out exceptions preventing the verifier from running the …
```

SREP-1453: Handle FailureTarget status for Jobs

---

examples/aws/terraform/vpc-proxied-explicit/assets/Caddyfile.tpl
examples/aws/terraform/vpc-proxied-explicit/assets/mitmproxy.service.tpl
examples/aws/terraform/vpc-proxied-explicit/assets/userdata.yaml.tpl
examples/aws/terraform/vpc-proxied-explicit/main.tf

The terraform scripts in our examples/aws/terraform directory have a dependency on a proxy tool called [mitmproxy](https://www.mitmproxy.org/). This PR updates that dependency to the latest version in order to include the latest security and bug fixes. This PR also makes changes to the Caddyfile necessary for addressing a breaking bugfix in mitmproxy. Finally, it also adds an ignore_tags directive so that running `terraform apply` again after installing a ROSA HCP machinepool into a generated subnet doesn't cause Terraform to try to remove the subnet tags added by the installer

Updated mitmproxy to 12.1.2 in explicitly proxied VPC Terraform examples
