pkg/cloudclient/aws/private.go
Change errors for a more graceful exit and readable error
=> Remove panics and handle errors gracefully in egress test

README.md, pkg/cloudclient/aws/private.go
...to avoid unnecessary buffer extensions
=> Small typo updates, added error message, updated string builder length

.gitignore, Makefile, build/Dockerfile, build/bin/network-validator.go, hack/app_sre_build_deploy.sh, hack/app_sre_build_push.sh, hack/app_sre_pr_check.sh, project.mk, standard.mk
Clean version of https://github.com/openshift/osd-network-verifier/pull/10
Fix: https://issues.redhat.com/browse/OSD-9227
=> feat: add deploy scripts

README.md, go.mod, go.sum, pkg/cloudclient/gcp/gcp_test.go
Some small linting changes added to README, GCP unit tests added.
=> [OSD-9042] Small Readme updates, GCP unit tests

project.mk
To reflect changes in: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/31704/diffs
=> change the image name as osd-network-verifier

README.md
preview of README.md can  be reviewed on: https://github.com/boranx/osd-network-verifier/tree/docs-image-update
=> docs: mention verifier image, fix indentation

pkg/output/output.go
Small change that only prints errors if they occur, otherwise prints that all tests pass
=> Cleaned up summary

pkg/cloudclient/aws/private.go
Fix: https://issues.redhat.com/browse/OSD-10622
=> config: reduce timeout to a reasonable value

build/bin/network-validator.go
Egress endpoint checks are embarrassingly parallelizable, so we should parallelize them. This PR does so by running `ValidateReachability()` in a goroutine, communicating errors (i.e., unreachable endpoints) via a `failures` channel. We also explicitly pass `host` and `port` into the anonymous goroutine to avoid out-of-order memory access issues.
This addresses [OSD-10647](https://issues.redhat.com/browse/OSD-10647), where a lack of parallelization caused the verifier to run for over 30 seconds. With this PR, the verifier binary (inside the docker image, not including instance creation time) takes less than 3 seconds to run.
=> Parallelize egress endpoint checks 

pkg/cloudclient/aws/private.go
Use helpers function for polling mechanism
reduce timeout for _waitfor_ from 20 mins to 2 min
Execution Example: 
```shell
Created instance with ID: i-05085ec6471a11109
EC2 Instance: i-05085ec6471a11109 Running
Gathering and parsing console log output...
Terminating ec2 instance with id i-05085ec6471a11109
Summary:
All tests pass!
Success
```
=> ref: reduce instance waitfor timeout - transform it using helpers

pkg/cloudclient/aws/private.go
update to a newer verifier image
=> bump verifier image

AWS.md, README.md
Added flow diagrams for better understanding
ref https://coreos.slack.com/archives/CMD1L32M9/p1652352722619129
=> Added flow diagrams in READMEs for better understanding

examples/firewall/README.md
Added a README.md for firewallConfig,go that contains the resources created, the permissions needed for the script and how to manually clean up after done with testing
=> README.md for firewallConfig.go

pkg/cloudclient/aws/private.go
Bumping the image version as part of the finalization of [OSD-11318](https://issues.redhat.com//browse/OSD-11318)
=> OSD-11318 - Bumping the image version

pkg/helpers/config/userdata.yaml
bug: currently validations are not executed as there's no docker installed.
=> bug: add docker back to the userdata

build/bin/network-validator.go
This PR adds retry behavior to the "network-validator" binary that gets baked into the Docker image, such that the binary will retry a failed endpoint connection attempt `maxRetries` times before declaring the endpoint unreachable. `maxRetries` is configurable via command line flag, and defaults to 3 attempts.
This addresses [OSD-12061](https://issues.redhat.com/browse/OSD-12061), where a lack of retry behavior has been found to cause false negatives (i.e., falsely claiming that an endpoint is blocked).
=> Add configurable endpoint connection retry feature

pkg/output/output.go
Cleaned up a comment and an error message for clarity
=> Minor text cleanup for clarification in errors

OWNERS
Planning to be active in this repo moving forward
=> Add mjlshen as a reviewer

README.md
- Docs
Fix the links to AWS docs
~~- [ ] I have commented my code, particularly in hard-to-understand areas~~
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have made corresponding change to the default configuration files~~
~~- [ ] I have added tests that prove my fix is effective or that my feature works~~
~~- [ ] I have tested the functionality against gcp / aws, it doesn't cause any regression~~
~~- [ ] I have added execution results to the PR's readme~~
=> Update the doc links for aws

pkg/verifier/aws/aws_verifier.go
Removes use of Public IP for AWS egress test
=> Remove public IP use

pkg/helpers/config/userdata.yaml
[OSD-13567](https://issues.redhat.com//browse/OSD-13567)
The 'Z' option for mounting volume will enforce labeling its content as 'private unshared' with Selinux. This way, volume is accessible in read/write but not accessible from other containers. 
In addition to standard testing, we need to ensure this is working end-to-end with proxy setup. I only confirmed access to the file so far.
=> OSD-13567 : Adding Z option to volume mount to have proper selinux labeling

README.md, docs/aws/aws.md
Updates the _README_ with the followings:
- fix docker image URL
- golden ami
- update egress list to the latest
=> docs: reflect ami works to docs

RELEASE.md, pkg/verifier/aws/aws_verifier.go
[OSD-15914](https://issues.redhat.com//browse/OSD-15914) - Updates the container image with the latest build corresponding with #176
```
❯ ~/git/openshift/osd-network-verifier/osd-network-verifier egress --subnet-id subnet-02537289237936c1c --security-group-id sg-094091624bada491b --region us-east-1         
Created instance with ID: i-06dd27b23f208d2f8
Summary:
All tests pass!
Success
```
=> Update quay image for AWS

RELEASE.md
Docs
added a step to update downstream project with the new verifier release
=> added a step to update downstream projects after creating a new release

pkg/verifier/aws/aws_verifier.go, pkg/verifier/aws/aws_verifier_test.go, pkg/verifier/aws/entry_point.go
Adds context from the verifier input to debug log calls
=> feat: Add context from vei to debug log calls

cmd/egress/cmd.go, pkg/clients/aws/aws.go, pkg/mocks/mock_aws.go, pkg/verifier/aws/aws_verifier.go, pkg/verifier/aws/entry_point.go, pkg/verifier/package_verifier.go
This PR adds creates a parameter which allows importing of a public ssh key to the created debug instance and cleans it up afterwards.
=> Add of pubKey to debug instance to allow ssh

pkg/verifier/aws/aws_verifier.go
=> adding regions ap-south-2 and ap-southeast-4

pkg/verifier/aws/entry_point.go
Added a new function, CleanupSecurityGroup that is defered to always be called at the end.
[OSD-16076](https://issues.redhat.com//browse/OSD-16076): https://issues.redhat.com/browse/OSD-16076
There is a bug where SGs are sometimes not being cleaned up when network-verifier is ran.  This is likely because there are multiple places that network-verifier can error out where the SG cleanup would not have been triggered.
New function CleanupSecurityGroup was written to manually clean up the security groups.  It uses the 'defer' keyword in Go to always to execute at the _end_ of the function it's nested in.  In this case, CleanupSecurityGroup should always be called even if a previous line errors out.
Logs from a local build that show when we pass an empty string as the SG and network-verifier …
=> (OSD-16076) osd-network-verifier security group not being cleaned up

pkg/verifier/aws/entry_point.go
Closes [OSD-20709](https://issues.redhat.com/browse/OSD-20709)
Adds log messages explaining what the verifier is doing during the instance/security group cleanup period
=> [OSD-20709] Added log messages for instance/security group cleanup

docs/aws/aws.md
- Docs
Updates the Documentation and Gives an example of using the new --force-temp-security-group flag
=> Update Docs and example of using new force-temp-security-group flag

build/config/aws.yaml, build/config/config.yaml, build/config/gcp.yaml, build/config/hostedcluster.yaml
add egress URL lists to verifier repo
[OSD-22627](https://issues.redhat.com//browse/OSD-22627)
=> copy URL lists from golden-ami repo

OWNERS
The codebase seems healthy enough without me and I'm not as active in this space lately.
=> mshen to emeritus_approvers

pkg/verifier/aws/entry_point.go
Adds a fallback to use the local list if we fail to parse the content in the github list after successfully fetching it.
Relates to [OSD-22628](https://issues.redhat.com//browse/OSD-22628)
=> Add fallback if we fail to convert github list to a curl string

pkg/data/cpu/cpu.go
Small comment fix for the ArchX86 Architecture. It should be about x86 and not arm.
- [NA] I have made corresponding change to the default configuration files
- [NA] I have added tests that prove my fix is effective or that my feature works
- [NA] I have tested the functionality against gcp / aws, it doesn't cause any regression
- [NA] I have added execution results to the PR's readme
Not applicable.
Not applicable.
=> Fix the ArchX86 comment for Architecture. It should be x86 and not arm.

README.md, docs/aws/aws.md
Updated the docs to include the following new flags: 
cpu-arch
egress-list-location
probe
Also udpated the docs to reflect how egress lists are maintained
https://issues.redhat.com/browse/OSD-24920
=> (OSD-24920) Update verifier docs to include new flags and probe behavior

README.md, RELEASE.md, docs/aws/aws.md
- Docs
Updates documentation to match the current state of the verifier.
[OSD-24417](https://issues.redhat.com//browse/OSD-24417)
=> Update docs to include new probe information along with other cleanup

pkg/data/egress_lists/aws-classic.yaml, pkg/data/egress_lists/aws-hcp.yaml, pkg/data/egress_lists/gcp-classic.yaml
Addresses [OSD-25873](https://issues.redhat.com/browse/OSD-25873) by removing unused endpoints
Standard testing process for network verifier. No special instructions.
N/A
=> OSD-25873: Removing unused endpoints from egress lists

OWNERS
Add myself as a reviewer for this project
=> Add joshbranham as a reviewer

README.md, docs/aws/aws.md, docs/gcp/gcp.md
Update documentation to include the new platform type interface.
ype of change
- Docs
https://issues.redhat.com/browse/OSD-25668
=> (OSD-25668) Update documentation to include new Platform interface

OWNERS
Add myself as an approver to this project based on the criteria discussed amongst the team.
=> Add joshbranham as an approver

cmd/egress/cmd.go, pkg/verifier/aws/entry_point.go, pkg/verifier/gcp/entry_point.go
BUG fix
Ignore caCert option passed if the noTls flag was set to true.
=> ignore any passed caCert when noTls option is set to true.

pkg/data/egress_lists/aws-hcp.yaml
[OSD-27967](https://issues.redhat.com/browse/OSD-27967)
=> OSD-27967: add missing Quay endpoints to ROSA HCP egress list

pkg/data/egress_lists/gcp-classic.yaml
[OSD-27965](https://issues.redhat.com/browse/OSD-27965)
=> OSD-27965: Update GCP Egress List to properly reflect documentation

pkg/data/egress_lists/aws-classic.yaml
[OSD-27966](https://issues.redhat.com/browse/OSD-27966)
=> OSD-27966: Clean up egress list for ROSA Classic/OSD-AWS

.ci-operator.yaml
This updates the `.ci-operator.yaml` file to use the latest boilerplate image. Currently, our CI config is such that _this file was never used_ which is misleading.
I am updating the project to use boilerplate properly, and in the process I needed to update this file before the changes in https://github.com/openshift/release/pull/63612 will work.
This pulls in Go 1.23 from boilerplate as the base CI image, then I can re-run rehearsals in https://github.com/openshift/release/pull/63612 which will then unblock linting failing in https://github.com/openshift/osd-network-verifier/pull/302
=> OSD-29370: Update `.ci-operator.yaml` for new boilerplate

.ci-operator.yaml
Bump the boilerplate image in the CI config, in prep for switching prow to use this file when configuring jobs, versus us setting an image in `openshift/release`. This brings the repo more in line with the rest of the OSD operators/projects.
=> OSD-29370: Update .ci-operator.yaml

Makefile
As part of adopting boilerplate for the CI image, we need to make sure we pass ${GOENV} around properly. I missed this one in the previous PR.
=> Plumb GOENV through for make fmt

OWNERS
=> Remove fahlmant from OWNERS
